- shell:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt update
  - sudo apt --assume-yes upgrade

- shell:
  - sudo apt --assume-yes install curl
  - sudo apt --assume-yes install guake
  - sudo apt --assume-yes remove cmdtest; sudo apt --assume-yes install yarn
  - sudo apt --assume-yes install zsh

- shell:
  - command: >
      sudo apt --assume-yes install \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - command: >
      sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
  - sudo apt update
  - sudo apt --assume-yes install docker-ce docker-ce-cli containerd.io



- shell:
  - sudo snap install code --classic
  - sudo snap install http
  - sudo snap install kubectl --classic
  - sudo snap install postman
  - sudo snap install slack --classic
  - sudo snap install spotify
  - sudo snap install telegram-desktop
