- shell:
    - defaults write com.apple.dock static-only -bool TRUE
    - defaults write com.apple.dock autohide -bool TRUE
    - defaults write com.apple.dock tilesize -int 56
    - defaults write com.apple.dock largesize -int 84
    - killall Dock

- brew:
    - httpie
    - wget
    - yarn

- cask:
    - caffeine
    - docker
    - firefox
    - iterm2
    - postman
    - rectangle
    - slack
    - spotify
    - telegram-desktop
    - the-unarchiver
    - visual-studio-code
