- shell:
    - description: "[zsh] Installing Oh-My-Zsh"
      command: >
        [ -d ~/.oh-my-zsh ] ||
        git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

    - description: "[zsh] Installing dracula theme"
      command: >
        [ -d config/zsh/themes/dracula ] ||
        git clone https://github.com/dracula/zsh.git config/zsh/themes/dracula

- link:
    ~/zshconfig: config/zsh/zshconfig
    ~/.zshrc: config/zsh/zshrc
    ~/.oh-my-zsh/themes/dracula.zsh-theme: config/zsh/themes/dracula/dracula.zsh-theme

- shell:
    - git update-index --skip-worktree config/zsh/zshconfig/local.sh
