- defaults:
    link:
        relink: true
        create: true
        force: true
    shell:
        stdout: true
        stderr: true

- clean: ["~"]

- link:
    ~/.gitconfig: config/git/gitconfig
    ~/.gitignore_global: config/git/gitignore
